name: nodejs application build
on: 
  workflow_dispatch:
    inputs:
      use-cache:
        description: 'Enable caching for node modules'
        default: true
        type: boolean
      node-version:
        description: 'Node.js version to use'
        default: '20.x'
        type: choice
        options:
          - '18.x'
          - '20.x'
          - '22.x'

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./node_app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version}}
      - name: Install dependencies
        run: npm ci 
      # - name: Run testing
      #   run: npm test
      # - name: Build application
      #   run: npm run build
      - name: Deploy application
        run: echo "Deploying application..."